services:
  app:
    build:
      context: .
    image: twitch-tts:latest
    restart: unless-stopped
    env_file:
      - ./twitchtts-data/.env
    environment:
      APP_ENV: prod
      DATABASE_PATH: var/app.sqlite
    ports:
      - "${TWITCHTTS_HTTP_PORT:-7317}:80"
      - "${TWITCHTTS_HTTPS_PORT:-8945}:443"
    volumes:
      - ./twitchtts-data/var:/var/www/html/var
      - ./twitchtts-data/certs:/etc/twitch-tts/certs
